language: r
r:
  - oldrel
  - release
  - devel
cache: packages

os:
  - linux
  - windows
  - osx

env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

warnings_are_errors: false

r_packages:
  - DiagrammeR

r_github_packages:
  - rich-iannone/DiagrammeRsvg
