language: r

# Test both linux and mac
matrix:
    include:
        - os: linux
          r: oldrel
        - os: linux
          r: release
        - os: linux
          r: devel
        - os: osx
          r: oldrel
        - os: osx
          r: release
        - os: osx
          r: devel
        - os: windows
          r: release
    allow_failures:
    # devel on osx fails
        - os: osx
          r: devel
        - os: windows
          r: release

cache: packages

env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

warnings_are_errors: false

r_packages:
  - DiagrammeR

r_github_packages:
  - rich-iannone/DiagrammeRsvg
