language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

warnings_are_errors: false

r_packages:
  - DiagrammeR

r_github_packages:
  - rich-iannone/DiagrammeRsvg
  
after_success:
  - Rscript -e 'covr::codecov()'
