language: r
r:
  - oldrel
  - release
  - devel
cache: packages

env:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

warnings_are_errors: false

r_packages:
  - DiagrammeR

r_github_packages:
  - rich-iannone/DiagrammeRsvg

install: travis_wait mvn install